name: Build Electron App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  bulid:
  
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [16.x]
      
    steps:
    - name: Get All Dependencies
      run: npm install 
    - name: Get Electron Forge
      run: npm install --save-dev @electron-forge/cli
    - name: Import Electron Forge
      run: npx electron-forge import
    - name: Build
      run: npm run make
        

        
